#!/usr/bin/env php

<?php

use Acme\DitBonjourCommand;
use Acme\DitBonsoirCommand;
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Console Demo', '1.1');

$app->add(new DitBonjourCommand);
$app->add(new DitBonsoirCommand);
$app->run();
